
services:
  phpadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - '9001:80'
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - ./phpmyadmin:/var/www/html/config.user.inc.php
  apache:
    build: .
    ports:
      - '8001:80'
    volumes:
      - ./website:/var/www/html/
    depends_on:
      - db
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: login_docker
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - '3307:3306'
    volumes:
      - ./db:/var/lib/mysql/
      
